version: 0.2

phases:
  build:
    commands:
      - echo Entering build phase...
      - echo Build started on `date`
      - mvn package
      - cd cfn
      - chmod +x prepare_template.sh
      - ./prepare_template.sh
      - aws cloudformation package --template aws-resources.yml --s3-bucket $S3_BUCKET --output-template template-export.yml
      - cp template-export.yml ../
artifacts:
  files:
    - template-export.yml